trigger:
- master
pool:
  vmImage: 'Ubuntu-18.04'
steps:

- task: DockerInstaller@0
  displayName: Install docker
  inputs:
    dockerVersion: '17.09.0-ce'
- script: |
    docker build -t caldito99/webapp .
    docker login -u $dockerId -p $(passwd)
    docker push caldito99/webapp

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Drop'
    publishLocation: 'Container'

